config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  
  root to: 'dashboard#show'
  
  get    'login'  => 'authentication#new',     as: :login
  post   'login'  => 'authentication#create'
  delete 'logout' => 'authentication#destroy', as: :logout
  
  get  'forgot_password' => 'password_resets#new', as: :forgot_password
  post 'forgot_password' => 'password_resets#create'
  
  get   'reset_password/:token' => 'password_resets#edit', as: :reset_password
  patch 'reset_password/:token' => 'password_resets#update'
  
  resources :users
  
  resources :games do
    scope module: 'games' do
      member do
        post   'invite'     => 'invite_mail#create', as: :send_invite_mail
        delete 'invite'     => 'invites#destroy',    as: :regenerate_invite
        get    'join/:code' => 'invites#update',     as: :join
      end
      
      post 'play'     => 'sessions#create', as: :create_session
      get  'play/:id' => 'sessions#show',   as: :play
      
      post 'chat/:session_id' => 'chat_messages#create', as: :chat
    end
  end
  
  resources :compendia do
    scope module: 'compendia' do
      resources :maps, only: %i[new create]
      resources :pages do
        resources :contents, controller: 'page_contents'
      end
      put 'pages' => 'pages#update_all', as: :update_pages
      get 'page_contents/new' => 'page_contents#new', as: :new_page_content
    end
  end
  
  resources :maps, except: %i[new create] do
    scope module: 'maps' do
      resources :areas
      resources :backgrounds
      resources :characters
      resources :floors
      resources :doors
    end
  end
  
  resources :dice_rolls, only: %i[index new create show]
  
  resources :account_activations, only: %i[edit create show]
end

app/models/map.rb
class Map < ApplicationRecord
  
  belongs_to :page,
    class_name: 'Page::MapPage',
    autosave:   true,
    dependent:  :destroy
  
  belongs_to :compendium
  
  has_many :game_sessions,
    foreign_key: 'current_map_id'
  
  has_many :floors,
    -> { order(level: :desc) },
    class_name: 'Map::Floor',
    dependent:  :destroy
  
  has_many :backgrounds,
    through: :floors
  
  has_many :characters,
    through: :floors
  
  has_many :areas,
    through: :floors
  
  has_many :walls,
    through: :floors
  
  has_many :doors,
    through: :floors
  
  before_validation :build_page,  on: :create
  before_validation :update_page, on: :update
  
  def width
    floors.map(&:width).max
  end
  
  def height
    floors.map(&:height).max
  end
  
  def build_page(attributes = {})
    super attributes.merge(compendium: compendium, title: title)
  end
  
  def update_page
    page.title = title
  end
end

app/models/map/area.rb
class Map::Area < ApplicationRecord
  
  has_many :area_pages,
    class_name: 'Map::AreaPage'
  
  has_many :pages,
    through: :area_pages
  
  belongs_to :floor
  
  delegate :map, to: :floor,
    allow_nil: true
  
  validate :validate_bounds_json
  
  def full_title
    [short_code, title].compact.join('. ')
  end
  
  def bounds_json
    @bounds_json || (bounds || []).to_json
  end
  
  def bounds_json=(new_bounds)
    @bounds_json = new_bounds
    
    if valid_json?(new_bounds)
      self.bounds  = JSON.parse(new_bounds)
      @bounds_json = bounds.to_json
    end
  end
  
  private
  
  def validate_bounds_json
    if @bounds_json.present? && !valid_json?(@bounds_json)
      errors.add(:bounds_json, :invalid)
      return false
    end
  end
  
  def valid_json?(json)
    JSON.parse(json)
    return true
  rescue JSON::ParserError => e
    return false
  end
end

app/models/map/area_page.rb
class Map::AreaPage < ApplicationRecord
  
  belongs_to :area,
    class_name: 'Map::Area'
  
  belongs_to :page
  
end

app/models/map/background.rb
class Map::Background < ApplicationRecord
  
  has_one_attached :image
  
  delegate :filename, to: :image,
    allow_nil: true
  
  belongs_to :floor
  
  delegate :map, to: :floor,
    allow_nil: true
  
end

app/models/map/character.rb
class Map::Character < ApplicationRecord
  
  has_one_attached :image
  
  delegate :filename, to: :image,
    allow_nil: true
  
  belongs_to :floor
  
  delegate :map, to: :floor,
    allow_nil: true
  
  delegate :compendium, to: :map,
    allow_nil: true
  
end

app/models/map/door.rb
class Map::Door < ApplicationRecord
  
  belongs_to :floor
  
  delegate :map, to: :floor,
    allow_nil: true
    
  delegate :compendium, to: :map,
    allow_nil: true
  
  after_save :relay_update
  
  def origin
    [origin_x, origin_y]
  end
  
  def origin=(v)
    self.origin_x = v.first
    self.origin_y = v.last
  end
  
  def destination
    [destination_x, destination_y]
  end
  
  def destination=(v)
    self.destination_x = v.first
    self.destination_y = v.last
  end
  
  private
  
  def relay_update
    return unless map.present?
    
    map.game_sessions.find_each do |session|
      GameSessionRelayJob.perform_later(session, data: ['DoorUpdated', [attributes]])
    end
  end
  
end

app/models/map/floor.rb
class Map::Floor < ApplicationRecord
  
  belongs_to :page,
    class_name: 'Page::FloorPage',
    autosave:   true,
    dependent:  :destroy
  
  belongs_to :map
  
  has_many :backgrounds,
    dependent: :destroy
  
  has_many :areas,
    dependent: :destroy
  
  has_many :walls,
    dependent: :destroy
  
  has_many :doors,
    dependent: :destroy
  
  has_many :characters,
    dependent: :destroy
  
  before_validation :build_page,  on: :create
  before_validation :update_page, on: :update
  
  validates :title,
    presence: true
  
  def width
    columns * grid_size
  end
  
  def height
    rows * grid_size
  end
  
  def grid_size
    50
  end
  
  def build_page(attributes = {})
    super attributes.merge(
      compendium: map.compendium,
      title:      title,
      parent:     map.page
    )
  end
  
  def update_page
    page.title  = title
    page.parent = map.page
  end
end

app/models/map/room.rb
class Map::Room < ApplicationRecord
  
  belongs_to :page,
    class_name: 'Page::RoomPage',
    autosave:   true,
    dependent:  :destroy
  
  belongs_to :floor
  
  delegate :map, to: :floor,
    allow_nil: true
  
  before_validation :build_page,  on: :create
  before_validation :update_page, on: :update
  
  validate :validate_bounds_json
  
  def full_title
    [short_code, title].compact.join('. ')
  end
  
  def bounds_json
    @bounds_json || (bounds || []).to_json
  end
  
  def bounds_json=(new_bounds)
    @bounds_json = new_bounds
    
    if valid_json?(new_bounds)
      self.bounds  = JSON.parse(new_bounds)
      @bounds_json = bounds.to_json
    end
  end
  
  def build_page(attributes = {})
    super attributes.merge(
      compendium: map.compendium,
      title:      title,
      parent:     floor.page
    )
  end
  
  def update_page
    page.title  = title
    page.parent = floor.page
  end
  
  private
  
  def validate_bounds_json
    if @bounds_json.present? && !valid_json?(@bounds_json)
      errors.add(:bounds_json, :invalid)
      return false
    end
  end
  
  def valid_json?(json)
    JSON.parse(json)
    return true
  rescue JSON::ParserError => e
    return false
  end
end

app/models/map/wall.rb
class Map::Wall < ApplicationRecord
  
  belongs_to :floor
  
  delegate :map, to: :floor,
    allow_nil: true
  
  def origin
    [origin_x, origin_y]
  end
  
  def origin=(v)
    self.origin_x = v.first
    self.origin_y = v.last
  end
  
  def destination
    [destination_x, destination_y]
  end
  
  def destination=(v)
    self.destination_x = v.first
    self.destination_y = v.last
  end
  
end

app/controllers/compendia/maps_controller.rb
module Compendia
  class MapsController < CompendiumController
    def new
      @map = @compendium.maps.new
    end
    
    def create
      @map = @compendium.maps.build map_params
      
      if @map.save
        redirect_to @map, notice: t('.map_created', map: @map.title)
      else
        raise @map.errors.inspect
        flash.now[:alert] = t('.map_invalid')
        render :new
      end
    end
    
    private
    
    def map_params
      params.require(:map).permit(%i[
        title
      ])
    end
  end
end

app/controllers/games/maps_controller.rb
module Games
  class MapsController < GameController
    def new
      @map = @game.maps.new
    end
    
    def create
      @map = @game.maps.build map_params
      
      if @map.save
        redirect_to @map, notice: t('.map_created')
      else
        flash.now[:alert] = t('.map_invalid')
        render :new
      end
    end
    
    private
    
    def map_params
      params.require(:map).permit(%i[
        title
      ])
    end
  end
end

app/controllers/maps/areas_controller.rb
module Maps
  class AreasController < MapController
    def show
      @area = @map.areas.find params[:id]
      redirect_to map_floor_url(@map, @area.floor)
    end
    
    def new
      @area = @map.areas.new area_params
    end
    
    def create
      @area = @map.areas.build area_params
      if @area.save
        redirect_to map_area_url(@map, @area), notice: t('.area_created')
      else
        flash.now[:alert] = t('.area_invalid')
        render :new
      end
    end
    
    def edit
      @area = @map.areas.find params[:id]
    end
    
    def update
      @area = @map.areas.find params[:id]
      
      if @area.update(area_params)
        redirect_to map_area_url(@map, @area), notice: t('.area_updated')
      else
        flash.now[:alert] = t('.area_invalid')
        render :edit
      end
    end
    
    private
    
    def area_params
      params.fetch(:map_area, {}).permit(%i[
        short_code
        title
        floor_id
        x y
        bounds_json
      ],
        page_ids: []
      ).tap do |area|
        area[:page_ids] = area[:page_ids].map { |id| id.presence&.to_i }.compact if area[:page_ids]
      end
    end
  end
end

app/controllers/maps/backgrounds_controller.rb
module Maps
  class BackgroundsController < MapController
    def show
      @background = @map.backgrounds.find params[:id]
      redirect_to map_floor_url(@map, @background.floor)
    end
    
    def new
      @background = @map.backgrounds.new background_params
    end
    
    def create
      @background = @map.backgrounds.build background_params
      if @background.save
        redirect_to map_background_url(@map, @background), notice: t('.background_created')
      else
        flash.now[:alert] = t('.background_invalid')
        render :new
      end
    end
    
    def edit
      @background = @map.backgrounds.find params[:id]
    end
    
    def update
      @background = @map.backgrounds.find params[:id]
      if @background.update(background_params)
        redirect_to map_background_url(@map, @background), notice: t('.background_updated')
      else
        flash.now[:alert] = t('.background_invalid')
        render :edit
      end
    end
    
    private
    
    def background_params
      params.fetch(:map_background, {}).permit(%i[
        image
        floor_id
        width
        height
        x
        y
      ])
    end
  end
end

app/controllers/maps/characters_controller.rb
module Maps
  class CharactersController < MapController
    def show
      @character = @map.characters.find params[:id]
      redirect_to map_floor_url(@map, @character.floor)
    end
    
    def new
      @character = @map.characters.new character_params
    end
    
    def create
      @character = @map.characters.build character_params
      if @character.save
        redirect_to map_character_url(@map, @character), notice: t('.character_created')
      else
        flash.now[:alert] = t('.character_invalid')
        render :new
      end
    end
    
    def edit
      @character = @map.characters.find params[:id]
    end
    
    def update
      @character = @map.characters.find params[:id]
      if @character.update(character_params)
        redirect_to map_character_url(@map, @character), notice: t('.character_updated')
      else
        flash.now[:alert] = t('.character_invalid')
        render :edit
      end
    end
    
    private
    
    def character_params
      params.fetch(:map_character, {}).permit(%i[
        name
        image
        floor_id
        width
        height
        x
        y
        light_color
        light_radius
        dim_light_radius
      ])
    end
  end
end

app/controllers/maps/doors_controller.rb
module Maps
  class DoorsController < MapController
    def edit
      @door = @map.doors.find params[:id]
    end
    
    def update
      @door = @map.doors.find params[:id]
      if @door.update(door_params)
        redirect_to map_floor_url(@map, @door), notice: t('.floor_updated')
      else
        flash.now[:alert] = t('.floor_invalid')
        render :edit
      end
    end
    
    private
    
    def door_params
      params.require(:map_door).permit(%i[
        origin_x      origin_y
        destination_x destination_y
        closed
      ])
    end
  end
end

app/controllers/maps/floors_controller.rb
module Maps
  class FloorsController < MapController
    def show
      redirect_to map_url(@map, floor_id: params[:id])
    end
    
    def new
      @floor = @map.floors.new
    end
    
    def create
      @floor = @map.floors.build floor_params
      if @floor.save
        redirect_to map_floor_url(@map, @floor), notice: t('.floor_created')
      else
        flash.now[:alert] = t('.floor_invalid')
        render :new
      end
    end
    
    def edit
      @floor = @map.floors.find params[:id]
    end
    
    def update
      @floor = @map.floors.find params[:id]
      if @floor.update(floor_params)
        redirect_to map_floor_url(@map, @floor), notice: t('.floor_updated')
      else
        flash.now[:alert] = t('.floor_invalid')
        render :edit
      end
    end
    
    private
    
    def floor_params
      params.require(:map_floor).permit(%i[
        title
        level
        columns
        rows
        scale
        scale_unit
        background_color
        grid
        grid_type
        grid_color
        grid_opacity
        global_illumination
      ])
    end
  end
end

app/controllers/maps/map_controller.rb
module Maps
  class MapController < ApplicationController
    
    before_action :require_user
    before_action :load_map
    
    private
    
    def load_map
      @map = Map.find params[:map_id]
    end
    
    def current_game
      @game ||= @map.game
    end
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  
  layout 'map_editor', only: :show
  
  def show
    @map = Map.find params[:id]
    @compendium = @map.compendium
    
    if params[:floor_id]
      @active_floor = @map.floors.find params[:floor_id]
    else
      @active_floor = @map.floors.first
    end
  end
  
  def edit
    @map = Map.find params[:id]
  end
  
  def update
    @map = Map.find params[:id]
    if @map.update(map_params)
      redirect_to map_url(@map), notice: t('.map_updated')
    else
      flash.now[:alert] = t('.map_invalid')
      render :edit
    end
  end
  
  private
  
  def map_params
    params.require(:map).permit(%i[
      title
    ])
  end
end

app/views/maps/_editor.html.erb
<%
active_floor = local_assigns[:active_floor]
active_panel = local_assigns[:active_panel]
%>
<section class="section">
  <div class="columns map-editor">
    <div class="column">
      <div data-controller="map--canvas" data-action="resize@window->map--canvas#resize" style="background: #c0c0c0">
      </div>
    </div>
    
    <div class="column is-full-mobile is-half-tablet is-one-third-desktop is-one-quarter-widescreen is-one-fifth-fullhd">
      <nav class="panel">
        <div class="panel-heading">
          <div class="level is-mobile">
            <h1 class="level-left"><%= map.title %></h1>
            <p class="level-right">
              <%=
                link_to t('.edit'),
                  edit_map_path(map),
                  class: 'button is-small',
                  data: { remote: true }
              %>
            </p>
          </div>
        </div>
        <% floors.each do |floor| %>
          <div class="panel-block<% if floor == active_floor %> is-active<% end %>">
            <div class="level is-mobile">
              <h2 class="level-left">
                <%= link_to floor.title, map_floor_path(map, floor) %>
              </h2>
              <p class="level-right">
                <%=
                  link_to t('.edit'),
                    edit_map_floor_path(map, floor),
                    class: 'button is-small',
                    data: { remote: true }
                %>
              </p>
            </div>
          </div>
        <% end %>
        <div class="panel-block">
          <%=
            link_to t('.new_floor'), new_map_floor_path(map),
              class: 'button is-small is-link is-outlined is-fullwidth',
              data:  {
                remote: true
              }
          %>
        </div>
        
        <% if floor = active_floor %>
          <p class="panel-tabs">
            <% %w[backgrounds].each do |panel| %>
              <%=
                link_to t(".#{panel}"), '',
                  class: ('is-active' if panel == active_panel)
              %>
            <% end %>
          </p>
          <% floor.backgrounds.each do |background| %>
            <div class="panel-block">
              <div class="level is-mobile">
                <h2 class="level-left">
                  <%= link_to background.filename, map_background_path(map, background) %>
                </h2>
                <p class="level-right">
                  <%=
                    link_to t('.edit'),
                      edit_map_background_path(map, background),
                      class: 'button is-small',
                      data: { remote: true }
                  %>
                </p>
              </div>
            </div>
          <% end %>
          <div class="panel-block">
            <%=
              link_to t('.new_background'), new_map_background_path(map, background: { floor_id: floor.id }),
                class: 'button is-small is-link is-outlined is-fullwidth',
                data:  {
                  remote: true
                }
            %>
          </div>
        <% end %>
      </nav>
    </div>
  </div>
</section>

app/views/maps/_form.html.erb
<%= bulma_form_for map do |f| %>
  <div class="modal-card">
    <header class="modal-card-head">
      <p class="modal-card-title"><%= t '.edit_map' %></p>
      <button class="delete" aria-label="close" data-action="click->modal#close"></button>
    </header>
    
    <section class="modal-card-body">
      <%= f.field :title do %>
        <%= f.label      :title %>
        <%= f.text_field :title %>
        <%= f.errors     :title %>
      <% end %>
    </section>
    
    <footer class="modal-card-foot">
      <%= f.button t('.submit'), type: 'submit', class: 'button is-success' %>
      <%= f.button t('.cancel'), type: 'reset',  class: 'button is-text', data: { action: 'click->modal#close' }%>
    </footer>
  </div>
<% end %>

app/views/maps/edit.js.erb
(function(modal) {
  modal.show('<%= escape_javascript render('form', map: @map) %>')
})(window.VTT && window.VTT.modal)

app/views/maps/show.html.erb
<%
title    @map.title
subtitle @compendium&.title
%>
<div class="map-editor">
  <%= render 'map/editor_toolbox', map: @map, active_floor: @active_floor %>
  <%= render 'map/editor_canvas',  map: @map, active_floor: @active_floor %>
  <%= render 'map/editor_sidebar', map: @map, active_floor: @active_floor %>
</div>